# SSC Configuration
ssc_mode: "fullnode"
ssc_moniker: "{{ moniker }}"
ssc_version: "1.0.0"
ssc_image: "sagaxyz/ssc:{{ ssc_version }}"
ssc_key_password: "{{ keychain_password }}"
ssc_start_args: "--rpc.laddr tcp://0.0.0.0:26657 --p2p.laddr tcp://0.0.0.0:26656 --grpc.address 0.0.0.0:9090"
ssc_additional_args: ""
ssc_pruning_strategy: "custom"
ssc_pruning_keep_recent: "1000"
ssc_pruning_interval: "100"

# SSC Resources
ssc_resources:
  requests:
    memory: "512Mi"
    cpu: "0.2"
  limits:
    memory: "1Gi"
    cpu: "0.5"
ssc_volume_size: "50Gi"

# StateSync
ssc_statesync_enabled: true
ssc_statesync_trust_interval: 1000

# Snapshots
ssc_snapshot_enabled: true
ssc_snapshot_interval: 1000
ssc_snapshot_keep_recent: 2
