# SSC Configuration
ssc_enabled: false
ssc_mode: "fullnode"
ssc_moniker: "{{ moniker }}"
ssc_version: "0.4.0"
ssc_image: sagaxyz/ssc:{{ ssc_version }}
ssc_validator_mnemonic: "{{ validator_mnemonic | default('') }}"
ssc_key_password: "{{ keychain_password }}"
ssc_start_args: "--rpc.laddr tcp://0.0.0.0:26657 --p2p.laddr tcp://0.0.0.0:26656 --grpc.address 0.0.0.0:9090"

# SSC Resources
ssc_resources:
  requests:
    memory: "512Mi"
    cpu: "0.2"
  limits:
    memory: "1Gi"
    cpu: "0.5"
ssc_storage_class: "saga-default"

# SSC Network
ssc_external_address: "127.0.0.1"
ssc_additional_args: ""

# SSC Genesis Download
ssc_genesis_download_timeout: 300
