# Chains config (spc and chainlets)
spc_chain_id: spc-1
spc_volume_size: 100Gi
s3_bucket: s3://mainnet-prod
quorum_count: 4
validator_addresses: saga1pdf6slnws5hqeg0wz5t4snrfzyx7wg7fra84q3 saga1954vr9dlykxxtmazesz3llntmdz7pn0ep07x6v saga1dque6vr4lzlkl0uqn6v6tdxys5g466jphah7d4 saga18u6dnjzd2gzh5fgprtwvx9adfwwn99qc6tagnh
stake_owner_address: saga1k70m2ms8kyta5749nz2t77ts0xt6229qcle9jg
foundation_wallet_address: saga1u2a8ktctqhpx655ysw7ru27t6hqt9wlq4fn5ca
is_testnet: false
controller_chainlet_pvc_size: "60Gi"
hub_chain_id: hub_5464111-1

# Enabled components
expose_p2p: true
metrics_enabled: true
statesync_enabled: true
metrics_alertmanager_enabled: true

# StateSync
statesync_rpc_domains:
  - spsrv1.sagarpc.io
  - spsrv2.sagarpc.io

# SSC
ssc_chain_id: "ssc-1"
ssc_denom: "usaga"
ssc_rpc: "https://ssc-rpc.sagarpc.io:443"
ssc_consumer_gas_price: "0.01"
ssc_genesis_url: "https://raw.githubusercontent.com/sagaxyz/mainnet/refs/heads/main/genesis/genesis.json"
ssc_volume_size: "100Gi"
ssc_rpc_servers:
  - https://ssc-rpc.sagarpc.io:443
  - https://ssc-statesync-us.sagarpc.io:443
ssc_peers: "fe0a7c342c3ea6934b89f87a4e5d93ae02792243@195.14.6.50:26014,7b205854267901c355fc1a18908764c118431375@51.81.167.206:17300,054b42595365063100789a218070023bb749c156@66.172.36.135:11156,8abc9ea7ab1db58c26eae9b55344644893f64d49@66.172.36.136:11156,4318a1fafa158df21b98d28bf5ed529f79db57c7@95.216.38.96:11156"
