# Chains config (spc and chainlets)
spc_chain_id: spc-staging-1
spc_volume_size: 50Gi
s3_bucket: s3://testnet-staging
quorum_count: 2
validator_addresses: saga10h0ngnu5cz0e2v5k6pdz2l5xhl3edhnlqvrdd2 saga1uhuu689scjs9jpcyuapzdvxdxyh3rz46n29cdn
stake_owner_address: saga1z3q8z0k6ygzs8krcd4u3s6ewa8de8nr645hh0l
foundation_wallet_address: saga1nmu5laudnkpcn6jlejrv8dprumqtj00ujl0zk2
is_testnet: true
controller_chainlet_pvc_size: "50Gi"
hub_chain_id: hub_5464113-1

# Enabled components
expose_p2p: true
metrics_enabled: true
statesync_enabled: true
metrics_alertmanager_enabled: false

# StateSync
statesync_rpc_domains:
  - staging-srv.sagarpc.io
  - staging1.sagarpc.io

# SSC
ssc_chain_id: "ssc-staging-2"
ssc_denom: "utsaga"
ssc_rpc: "http://34.9.0.15:26657"
ssc_grpc: "http://34.9.0.15:9090"
ssc_consumer_gas_price: "0.01"
ssc_genesis_url: "https://saga-public-assets.s3.us-east-1.amazonaws.com/genesis/staging/{{ ssc_chain_id }}_genesis.json"
ssc_peers: "08adf15cd7ea8bae8012234d581ce7741f587083@34.9.0.15:26656"
ssc_volume_size: "50Gi"
ssc_rpc_servers:
  - https://spc.staging-srv.sagarpc.io:443