# Chains config (spc and chainlets)
spc_chain_id: spc-testnet-2
spc_volume_size: 25Gi
s3_bucket: s3://testnet-prod-v2
quorum_count: 4
validator_addresses: saga1atjuvcf4aq3upr5eacacpv08lkp39v8208gw6z saga12uch6j240eqv5zgpr4f4zyy4c3gf923ky9qyru saga1hvm67hnpmfc5pfpeqqmung4kjqcavzatjegxu9 saga1q3u9efga08n5drr9takxe0q2qnjvmqymguna4u
stake_owner_address: saga162k9aqdgagr6qwjugqaktfycaechhnpzgl3rgs
foundation_wallet_address: saga1u2a8ktctqhpx655ysw7ru27t6hqt9wlq4fn5ca
is_testnet: true
controller_chainlet_pvc_size: "50Gi"
hub_chain_id: hub_5464111-1

# Enabled components
expose_p2p: true
metrics_enabled: true
statesync_enabled: true
metrics_alertmanager_enabled: true

# StateSync
statesync_rpc_domains:
  - st1.sagarpc.io
  - stsrv1.sagarpc.io

# SSC (disabled by default for testnet)
ssc_chain_id: "ssc-testnet-3"
ssc_denom: "utsaga"
ssc_rpc: "https://testnet2-keplr.sagarpc.io:443"
ssc_consumer_gas_price: "0.01"
ssc_grpc: "https://testnet2-grpc.sagarpc.io:9090"
ssc_genesis_url: "https://raw.githubusercontent.com/sagaxyz/testnet-2/refs/heads/main/genesis/genesis.json"
ssc_volume_size: "25Gi"
