# Chains config (spc and chainlets)
spc_chain_id: spc-testnet-2
spc_volume_size: 25Gi
s3_bucket: s3://testnet-prod-v2
quorum_count: 4
validator_addresses: saga1atjuvcf4aq3upr5eacacpv08lkp39v8208gw6z saga12uch6j240eqv5zgpr4f4zyy4c3gf923ky9qyru saga1hvm67hnpmfc5pfpeqqmung4kjqcavzatjegxu9 saga1q3u9efga08n5drr9takxe0q2qnjvmqymguna4u
stake_owner_address: saga162k9aqdgagr6qwjugqaktfycaechhnpzgl3rgs
foundation_wallet_address: saga1u2a8ktctqhpx655ysw7ru27t6hqt9wlq4fn5ca
is_testnet: true
controller_chainlet_pvc_size: "50Gi"
hub_chain_id: hub_5464111-1

# Enabled components
expose_p2p: true
metrics_enabled: true
statesync_enabled: true
metrics_alertmanager_enabled: true

# StateSync
statesync_rpc_domains:
  - st1.sagarpc.io
  - stsrv1.sagarpc.io

# SSC (disabled by default for testnet)
ssc_chain_id: "ssc-testnet-3"
ssc_denom: "utsaga"
ssc_rpc: "https://testnet2-keplr.sagarpc.io:443"
ssc_consumer_gas_price: "0.01"
ssc_grpc: "https://testnet2-grpc.sagarpc.io:9090"
ssc_genesis_url: "https://raw.githubusercontent.com/sagaxyz/testnet-2/refs/heads/main/genesis/genesis.json"
ssc_volume_size: "25Gi"
ssc_rpc_servers:
  - https://testnet2-keplr.sagarpc.io:443
  - https://testnet2-statesync-us.sagarpc.io:443
ssc_peers: "09ae7e33d0e0df33d902a6a9ad06788716194420@148.72.141.31:26746,35774fc7becf605fe1e72cad58248fef3281d8f1@146.59.71.233:26656,36e86608e53f380c1afc43091385e8b7eccafb95@85.195.103.141:26616,4ad8c47ad3940c97b74fe933140e8f947b0bdde5@135.181.180.144:26656,4f4563e3281123306fab1c719035b55acf20465f@5.0.1.1:26656,708816e0c3d29c678c6b99f5faa4a04b1d25e479@49.51.136.210:26656,711bbc430347ae4034e2e3058db0a9bbc0f3c9c0@148.113.166.142:26656,85f095ef934d27835aec0d6bb193c21e4fbf7fa7@8.40.118.100:26656,9d15565cbef6e1f630e8875ac358dee42f4530eb@80.64.208.45:26656,9f4c235f6e0cd92cead666ed9560eb16abe3d4ab@157.180.51.61:26656,a762a13416b5d9e8c8c7786ca2df0b06f6bc326d@93.115.24.179:26656,a9f1adfe11bdd159419913d23e24a4286c12fad3@185.100.10.191:26656,b6ca5ebbd92d7db97ef697b6a7e3d940c33cfab0@3.133.168.59:26656,c743d25ea8a21b2dde56f75fd0af54383bcdd7d4@46.62.137.218:26656,c9377aab40b7361c1705dfdf4526035ecfa9518c@65.21.111.137:26656,d96e9b856df55472b4e1050af08063143c68a86a@165.154.224.37:26656,df98f56c154abd056f3783e424f7f594126c09aa@103.88.234.227:26656,fb3fb3ccdbbedeba19cc0d7f1767ad93b42152e4@162.62.209.235:26656,4cbd2ae71e1cd58d64568a95a7f24d0bdf86cb83@184.107.182.148:57600"