# Controller config
controller_version: "0.11.0"
controller_image: "sagaxyz/controller:{{ controller_version }}"
controller_resources:
  requests:
    memory: "2Gi"
    cpu: "1"
  limits:
    memory: "4Gi"
    cpu: "2"
chainlet_template_dest: "/tmp/chainlet.yml.tmpl"
controller_lb_port_limit: 1000

# Chainlet vars
controller_chainlet_resources:
  requests:
    memory: "1Gi"
    cpu: "0.5"
  limits:
    memory: "4Gi"
    cpu: "2"

# Relayer vars
controller_relayer_enabled: false
controller_relayer_version: "0.4.2"
controller_relayer_wait_time: "0"
# Load Balancer Configuration
controller_chainlet_external_traffic_policy: Cluster
controller_chainlet_allocate_loadbalancer_node_ports: false

# Signer
controller_remote_signer_enabled: false